[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate --schema=packages/db/prisma/schema.prisma"
]

[start]
cmd = "npx tsx apps/api/src/index.ts"
